apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-container
          image: vinita2204/node-app:latest
          ports:
          - containerPort: 2222
            protocol: TCP
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: mysql-secret
      